README.md, entrypoint.sh
=> Remove -imgref from the entrypoint and document user customization

bib/cmd/bootc-image-builder/image.go, bib/go.mod, bib/go.sum, test/test_smoke.py, test/testutil.py
This test ensure that we build images without selinux denials in the logs.
=> HMS-3141: tests,bib: fix/check that there are no selinux denials

README.md
I've tested the latest container references and updated the readme to reflect it.
=> readme: Update container references in example

README.md
Noticed while building the integration test for this.
=> README.md: update -config->--config

README.md, bib/cmd/bootc-image-builder/cloud.go, bib/cmd/bootc-image-builder/main.go, bib/cmd/upload/main.go, bib/internal/uploader/aws.go, test/README.md, test/requirements.txt
Just using awscloud.NewDefault() should cover all usecases of AWS authentication.
=> HMS-3305: add support for authentication profiles

README.md
=> update readme to include the `key` and add `--config` arg to first example

test/test_smoke.py, test/testutil_test.py
This commit tweaks the image tests to use indirect fixtures when creating the images. This allows to write something like:
```
sudo pytest-3 -k 'test_image_is_generated[ami]'
```
to select only specific images to test.
Note that this also contains a tiny fix (in it's own commit) for yet another netcat commandline flavor. I can create a separate PR for this if desired, it's not strictly needed for this PR.
=> test: use indirect `pytest.mark.parametrize` to build image

README.md
We got some feedback that the summary in the README is a bit vague. This is an attempt to make it more concrete but also to keep it still short.
=> README.md: add tl;dr summary

.github/workflows/tests.yml
=> github: add AWS secrets to env vars for integration tests

.github/workflows/stale-cleanup.yml
We use it in all other projects, so let's use it here too.
=> github: set up the stale action here

.github/workflows/tests.yml, plans/all.fmf, test/test_build.py, test/testcases.py, test/vm.py
This is a continuation of https://github.com/osbuild/bootc-image-builder/pull/139 with the tests and a bit of extra setup in GH so that a disk with more space is used for the image building. That seems to solve the diskspace issue.
=> test: test cross building (amd64->aarch64)

README.md
The real motivation is to just get a new "dummy" commit in to see if https://github.com/osbuild/bootc-image-builder/issues/184 is fixed.
=> README.md: Fix a variety of markdown lints

devel/Containerfile
Use `package-requires.txt` here too, this helps
keep things in sync.
=> devel/Containerfile: Unify with main Containerfile

devel/Troubleshooting.md
This was useful to me to debug an issue.
=> troubleshooting: Describe how to run osbuild manually

README.md, bib/cmd/bootc-image-builder/build_type.go, bib/cmd/bootc-image-builder/main.go
Updated valid image types based on the current supported options
=> Updated missing types in help and docs

Containerfile
To pick up the recent opt-usrlocal change.
=> build: fast-track newer rpm-ostree

README.md
=> doc:add --cpu host in virt-install cli

Containerfile
Signed-off-by: John Eckersberg <jeckersb@redhat.com>
=> Add additional metadata labels as required downstream

README.md
Add documentation for running cross-architecture bib
I might have used too many words :)
=> add doc on cross-arch builds

bib/cmd/bootc-image-builder/main.go
The existing code is trying to fetch two containers when doing a cross-arch image. The buildroot is run in the native architecture and only the target tree is run non-native. However it turns out this is not neccessary as even doing the buildroot in non-native is fast enough (given that it's mostly I/O and all I/O is run naively via syscall translation).
So this commit removes the fetching of the native arch container for the buildroot. Note that in practise this was already the case when passing --target-arch to any container that had native build available. Here due to a bug/misfeature in the resolver library used it already resolved (incorrectly) to the target architecture and nobody noticed because it was good enough (after [0] got fixed).
[0] …
=> bib: use target architecture for buildroot as well

test/test_build.py
We are currently not testing that when the build image has a valid `bootc status` that container the original container reference.
Alternative version to https://github.com/osbuild/bootc-image-builder/pull/357 that works without creating a root user which seems broken right now on fedora but that needs to get investigated later.
=> test: check that `bootc status` contains the right container_ref

bib/cmd/bootc-image-builder/main.go
There doesn't seem to be much usage of logrus here, but I find debug logging very useful.
=> main: Wire up --log-level, add some debug logging

README.md
The current command fails if no mounted containers storage, add podman mount to fix it.
=> Add missing volume mount to README

Containerfile
=> Fix the linting error

bib/cmd/bootc-image-builder/main.go
When we run `podman pull` there is a *long* pause in the output. With that `bib` appears hanging. But `podman` prints progress on stderr so connect that give us a better user experience without polluting the `stdout` fd which needs to be pure `json` for
`bootc-image-builder manifest`.
This is a first step towards a more user friendly output from `bib`. Eventually we should probably wrap the podman progress into our own progress bar, there is an issue in podman [0] with some discussion how to do that but it requires a bunch more work.
[0] https://github.com/containers/podman-desktop/issues/152
[A different take to https://github.com/osbuild/bootc-image-builder/pull/286]
=> bib: when doing a `podman pull` connect stderr

.github/workflows/tests.yml, test/conftest.py, test/requirements.txt, test/test_build.py, test/test_flake8.py, test/test_manifest.py, test/test_opts.py, test/test_pylint.py, test/testcases.py, test/testutil.py, test/testutil_test.py, test/vm.py
Given that our testsuite is relatively complex it seems nice to let pylint have an opinion about it :)
This commit adds the needed test and also fixes the various issues it found.
=> test: add pylint on our test

bib/cmd/bootc-image-builder/partition_tables.go, bib/go.mod, bib/go.sum, bib/internal/uploader/aws.go, bib/internal/uploader/aws_test.go
This is needed to build bib with the current images library.
=> go.mod update to current images

test/test_manifest.py
Followup for https://github.com/osbuild/bootc-image-builder/pull/709 that adds a test.
This commit adds a quick manifest level test that ensures that the
FIPS customizations set for the iso installer are actually set
in the manifest.
=> test: add test that ensures fips customizations work

bib/data/defs/heliumos-10.yaml, bib/data/defs/heliumos-9.yaml
=> Add manifests for HeliumOS

.github/workflows/tests.yml
=> github: bump ubuntu runners to 24.04

README.md
README: Add containers-storage volume mount to examples
---
README: Misc whitespace fix
=> README: Add containers-storage volume mount to examples
