Containerfile
README.md
entrypoint.sh
prepare.sh

When building an image, we need to make sure that the target system is
correctly labeled. This becomes challenging if the target system contains
labels that are unknown to the host because the process setting the label
needs to have CAP_MAC_ADMIN if the host is SELinux-enforcing.
CAP_MAC_ADMIN isn't a common capability on a SELinux-enforcing system.
Even unconfined_t doesn't have it (same for spc_t - label used by
--privileged containers). Thus, we need to ensure that we transition to
a domain that actually has it.
This commit relabels osbuild as install_t, a domain that has CAP_MAP_ADMIN.
A bit of mount-dancing is needed in order to achieve that, see prepare.sh.
I decided to make prepare.sh a separate script. This is useful for debugging:
host # podman run -it \
--privileged \ …

Make the container work on an SELinux-enforcing systems

---

.github/workflows/build.yaml

I just enabled the merge queue for this repository.  Let's run the container build workflow on the queue.

github: run build workflow on the merge queue

---

Containerfile
group_osbuild-osbuild-fedora-39.repo

Builds are failing on certain systems on:
```
AttributeError: 'Loop' object has no attribute 'fd'
osbuild.host.RemoteError: FileNotFoundError: [Errno 2] No such file or directory: 'loop1'
```
This happens because /dev in a container is a statically created tmpfs. Thus, when a new loop device is allocated, it doesn't appear in the container. A newer version of osbuild fixes that by always making sure that the loop device exists (by simply calling `mknod`).
Pull the fix from COPR to unblock us, instead of waiting for the fix to flow into stable Fedora.
`dnf copr enable` requires `dnf-plugins-core` that's not installed by default. Let's just use a static .repo file instead, it feels a tad bit simpler.
Fixes #7 
Fixes #9

Containerfile: Install osbuild from COPR to pull a fix for the loop bug

---

.github/dependabot.yml
.github/workflows/auto-merge-dependabot.yml
.github/workflows/tests.yml
odc/cmd/osbuild-deploy-container/main.go
odc/go.mod

Let's add these now so we can have them run on #11

GitHub workflows: lint and dependabot

---

.github/workflows/testingfarm.yml

This adds initial testing farm integration via a github action. To run jobs on testing farm a token is required that is stored as a repository secret. For security reasons repository secrets are not visible accross forks [0].
There are multiple ways to work around this limiation, this commit goes with the suggestion from [1], i.e.: the workflow is run within the `pull_request_target` trigger which has access to secrets.
This means the (potentially untrusted) branch is only checked out if the person triggering the workflow has already write access to the repository (we could make this restriction strong but it seems a reasonable permisson level). In practise the workflow will fail for outside contributions but a re-trigger from anyone in the term should be enough to get it tested inside …

HMS-3162: tests: add initial testing farm integration

---

.github/workflows/testingfarm.yml

This is required apparently even when passing a `git_ref` to the testing farm github action. Sadly it was impossible to test this beforehand in the repo.

github: checkout code for testingfarm workflow first

---

.github/workflows/testingfarm.yml

In order to use nested virtualizaton we need to use the `Red Hat Ranch` from testing farm. The testing farm token is now updated in the github secrets. However the default value of the `sclorg/testing-farm-as-github-action@v1` action is to use `compose: Fedora-latest`. According to:
https://docs.testing-farm.io/Testing%20Farm/0.1/test-environment.html#_composes this is not available in the RH ranch so we need to use something else.
I picked `Fedora-39` for now but happy about alternative ideas (`CentOS-Stream-9` might also be an option?).

github: update `compose:` value for testing farm GH action

---

.github/workflows/testingfarm.yml
.github/workflows/tests.yml
plans/all.fmf
test/test_smoke.py
test/testutil.py
test/testutil_test.py
test/vm.py

This PR adds the extra check that the generated image from `podman run osbuild-deploy-container` can actually boot in qemu and will open the ssh port.

HMS-3162: test: boot generated image and ensure ssh is working

---

.github/workflows/build.yaml

While this would be great, the build check is required, thus we cannot skip it. Let's disable the condition as a quick workaround for now.

github: don't skip the build pipeline on README-only PRs

---

.github/workflows/tests.yml
plans/all.fmf
test/test_smoke.py
test/vm.py

This commit adds an integration test that ensures that the generated
disk can be logged into via ssh by the blueprint user.
Build on top of https://github.com/osbuild/bootc-image-builder/pull/34

tests: actually log into the generated disk image

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml
test/test_smoke.py
test/testutil.py
test/testutil_test.py

The existing test_smoke was becoming a bit too big and especially the fact that part have to be skipped depending on the environment is really not nice.
This commit refactors it to be more module. For this it uses the pytest session scope to ensure that the build container and the test image are only build once and then shared accross the various individual tests.

test: refactor monolithic `test_smoke` into multiple tests

---

.gitignore
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
test/test_smoke.py

Add support for building an AMI with a `--type` flag.  The only difference between the qcow2 and the AMI is the output file format, which for AMI is raw.
The default image type is qcow2.
Tests now build and boot both image types.

HMS-3276: Add support for building AMIs

---

bib/cmd/bootc-image-builder/main.go
bib/go.mod

Before
```
$ podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v $(pwd)/output:/output quay.io/centos-bootc/bootc-image-builder:latest quay.io/centos-bootc/fedora-bootc:eln --type ami
Generating manifest for empty: WARN[0000] Failed to load consumer certs: no consumer key found
DONE
Building manifest: /output/manifest.json
```
After
```
$ podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v $(pwd)/output:/output quay.io/centos-bootc/bootc-image-builder:latest quay.io/centos-bootc/fedora-bootc:eln --type ami
Generating manifest-ami.json ... DONE
Building manifest-ami.json
```

Make the initial output of the command nicer

---

Containerfile

If we firstly copy go.mod and go.sum in and call go mod download, we get a cached layer with the go dependencies. This is useful for developers, because you only need to redownload the dependencies if go.mod or go.sum actually change.

Containerfile: Enable basic caching of go deps

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go

This is unfortunately a bigger PR that I would have liked, but everything is sorta interconnected. 3 major things happening:
1) I created a new struct called `ManifestConfig` to hold everything needed to create a manifest. Adding new options with this struct is super-simple, and we also don't have functions accepting 6 arguments anymore.
2) I added a `--tls-verify` flag that allow disabling TLS verification. This is basically taken directly from `podman`.
3) I tweaked the README a bit. Arguments, image types and volumes are now tables. Customizations are now more properly documented. There are now emojis. I like them mostly because I think they add a lot of visual clarity where a section starts and where it ends.
You can see the tweaked readme here: …

Refactor, add --tls-verify and rework README

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go

image: Hoist up hardcoded constant, add TODO
To make it more obvious we should fix this.
---
Remove extraneous newlines from errors
My go linter correctly warns about these; the error
printer will include a newline as needed.
---
image: Add a TODO for kargs
This will go away when we use bootc.
---

A few minor patches

---

bib/cmd/bootc-image-builder/export_test.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/bootc-image-builder/main_test.go
bib/go.mod
bib/go.sum

osbuild uses `cp -a` to export artifacts from a build and files are (usually) owned by root.  The `cp` command tries to set the ownership to root on the mounted volume from the host but if it's running in a podman machine, this will fail.
Added a new check, `canChownInPath()`, which creates a temporary file in the output directory and tries to `chown` it to the uid and gid of the caller.  This lets us know if osbuild will be able to preserve the permissions of the output file when copying the results, which should be created with the uid and gid of the caller of osbuild, to the output directory.
This is used to set export option when calling osbuild, `OSBUILD_EXPORT_FORCE_NO_PRESERVE_OWNER`.  The option prevents osbuild from trying to set the ownership of the files in the destination and …

Fix artifact ownership problems

---

.github/workflows/tests.yml
test/requirements.txt
test/test_smoke.py
test/testutil.py
test/testutil_test.py
test/vm.py

This is a rebase/update of https://github.com/osbuild/bootc-image-builder/pull/33 without hacks.

tests: run integration test on macos GH runners as well

---

test/test_smoke.py

There is a desire to resue our tests to also test when new bootc containers are generated that they still build and boot. To do this we need a way to customize the tests further so that: a) we can omit building our code and instead use a "stable" container
that contains bootc-image-builder
b) we can specificy what bootc (target) image to test so that the
bootc building team can point to their staging area
This is currently done via environment variables. It might be worth exploring the pytest commandline option support [0] but that can be done in a followup.
[0] https://docs.pytest.org/en/7.1.x/example/simple.html

test: add `BIB_TEST_{BUILD,BOOTC}_CONTAINER_TAG` to customize tests

---

.github/workflows/tests.yml

Otherwise we can operate on cached metadata and fail.

ci: Ensure we `apt update` before `apt install`

---

.github/workflows/testingfarm.yml

Add the AWS secrets to the testing farm action so we can run the AWS upload test in TF.
Opening this PR separately to get this into `main` for #93, since adding the change in the PR wont have an effect before it's merged.

github: add AWS secrets to testing farm action

---

.github/workflows/tests.yml
README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go

Needs: https://github.com/osbuild/images/pull/322

iso: be able to build the ISO

---

.github/workflows/tests.yml
plans/all.fmf
test/conftest.py
test/requirements.txt
test/test_smoke.py
test/testutil.py
test/testutil_test.py
test/vm.py

When building a test AMI, upload it to AWS and boot it there, running the same smoke test as we do for the qcow2.
The local testing of the AMI is still run as before.
Added two subclasses to the VM class:
- QEMU: is the old code that initialises and boots an image in qemu.
- AWS: new code that launches (and terminates) an AMI.

Boot test AMIs in AWS

---

bib/cmd/bootc-image-builder/image.go

Anaconda uses the product name in the buildstamp when calling efibootmgr when setting up the bootloader for containers without bootupd.
Without the product name, the bootloader setup just crashed. This was manually verified using ghcr.io/ublue-os/silverblue-main:39.
See
https://github.com/rhinstaller/anaconda/blob/a8c654b406d128e0e423f4f892511374cc5258f7/pyanaconda/modules/storage/bootloader/efi.py#L88
Closes #114

bib/image: set the product name for the ISO

---

bib/cmd/bootc-image-builder/main.go

Listing regions *early* in main.go is just a way to check if the credentials somehow work and fail/exit otherwise.
The upload is not guaranteed to work like this but might be a good indicator.

main: check credentials by listing regions HMS-3329

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
test/test_smoke.py

A super simple PR to allow to get "raw" output for https://github.com/osbuild/bootc-image-builder/issues/99 
Right now this will be identical to an "ami" but it seems cleaner to me to me to separate the two as the may(?) diverge in the future.

bib: add "raw" image format

---

bib/cmd/bootc-image-builder/main.go
test/containerbuild.py
test/test_build.py
test/test_manifest.py

This was discussed some days ago: sometimes it is desirable to not actually generate the image directly but only generate the `manifest.json` description for the osbuild tool so that osbuild can generate the image. This is mostly useful for debugging and during development when e.g. new features in osbuild are used that are not yet part of the osbuild version inside the container or when we need debug data from users/customers to reproduce a failure.
Now that we have a `bootc-image-builder build` term we can have a `manifest` one as well that just generates the manifest but does not do the full building. This is mostly useful for testing so it's not exposed by default in the entrypoint (for now).

bib: implement `bootc-image-builder manifest`

---

test/testutil.py

Support for `match` in python is only available in version 3.10. However centos/rhel 8 and 9 have lower versions so this will need to be moved to `if/elif/else` for now.
See https://github.com/osbuild/bootc-image-builder/pull/109

testutil: remove "match" for centos8/9 compatbility

---

README.md

I had issues with the instructions when attempting the process on a brand new AWS account for testing. This will solve https://github.com/osbuild/bootc-image-builder/issues/127

README: Added prerequisites section to AWS documentation

---

.github/workflows/tests.yml
plans/all.fmf
pytest.ini
test/containerbuild.py

See the individual commits, this PR fixes three things:
1. asks tmt for more diskspace in general
2. move default /tmp for pytest to /var/tmp so that we do not suffer from tmpfs smallness
3. move to last known good quay.io/centos-bootc/fedora-bootc container before issues https://github.com/CentOS/centos-bootc/issues/184 and https://github.com/osbuild/bootc-image-builder/issues/149
This unblocks "main" but we still need to find a proper solution for (3)
--- 
The tests are currently running out of disk space inside the testing-farm environment. This commit should help debug this by adding `df -h` output after the test is run.
It also asks for 200GB disk space (which is probably way more than we need). Note that the docs say that the size is 250GB by default for things running inside the RH …

many: unbreak integration tests

---

build.sh

The default depends on btrfs, etc. that we don't need because ultimately we're just forking off skopeo anyways.

build: Use tags to trim down containers/storage dependencies

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go

This PR tweaks the code a bit to pass more errors up and exit only on the caller side. This will make writing unit tests easier and also feels a bit more goish. 
Split into multiple individual commits to see the refactor chain but it's fine to also just merge via a single squash, the history is really not that interesting :)

many: refactor usage of check/fail a bit

---

bib/cmd/bootc-image-builder/main.go

This pairs with usage of `RunE`, xref
https://github.com/osbuild/bootc-image-builder/commit/38ce0dacfcc997312710cacf351b95b9ea0c76b6

main: `SilenceUsage: true` by default

---

.github/workflows/tests.yml
bib/cmd/bootc-image-builder/fedora-eln.json
test/requirements.txt
test/test_build.py
test/vm.py

Add a new integration test that checks that the container installer
is working. The contaner installer just does an unattended install
of a disk. The test will run qemu with the installer.iso and an
empty disk. Once a reboot from the ISO is detected (via QMP) qemu
exists and boots the test disk and checks that it boots and the
test user can login.

test: add container installer test

---

.github/workflows/tests.yml

We have a bunch of false positive test failures like:
```
Check failure on line 4 in bib/cmd/bootc-image-builder/partition_tables.go
GitHub Actions / ⌨ Lint
"github.com/osbuild/images/pkg/arch" imported and not used (typecheck)
```
It turns out this happens when golang-ci cannot compile the code. And that happened because the (indirect) imports from the container libraries need libbtrfs-dev and libdevmapper-dev to compile.

github: fix golintci typecheck errors

---

.github/workflows/tests.yml
plans/all.fmf
pytest.ini
test/containerbuild.py
test/test_build.py
test/test_manifest.py
test/testcases.py

Build on top of https://github.com/osbuild/bootc-image-builder/pull/148
This PR adds code to speed up the tests by re-using images as much as possible. Ideally it would always share but because GH runners have constraint diskspace it will cleanup when the free space falls below 1GB (a bit arbitrary but should be a reasonable heuristic).

test: cache images when possible 

---

bib/cmd/bootc-image-builder/main.go

This commit adds experimental cross arch building.
I.e. you `bootc-image-builder` on a mac and target an `amd64` machine.
The usage would be:
```
sudo podman run ... \
--type qcow2 \
--target-arch amd64 \
quay.io/centos-bootc/fedora-bootc:eln
```
and this is predicated on the idea that the target container is available for both host and target architecture. When that is the case the container for the host architecture is used as a buildroot, the container for the target architecture is the target tree. Note that some stages chroot into the target tree so `qemu-user` is essential for this to work so that target achitecture code can be run transparently (because only very small amounts of code need to run emulated this is pretty fast still).
It will need qemu-user{,-static} installed on the …

bib: add cross arch building

---

devel/Containerfile
devel/README.md

New Containerfile that requires build contexts pointing to checked out sources for osbuild/osbuild and osbuild/images to make building development versions of all the components more convenient.
PR includes a README describing how to build the container.

Add Containerfile for building from osbuild and images sources for development

---

Containerfile
package-requires.txt

This is part of reusing the bib container to build base images; rpm-ostree wants to have *a* policy to bootstrap from currently.
For distribution-gpg-keys, it allows `.repo` files to reference those unconditionally.
Also, reuse a "make package lists declarative" model I've used in other places.  It'd be nice to try to semi-standardize this of course, or even better upstream it into dnf.
We're looking at adding a different Containerfile in https://github.com/osbuild/bootc-image-builder/pull/174 and this way it can source the same requirements.

Add selinux-policy-targeted and distribution-gpg-keys

---

bib/cmd/bootc-image-builder/main_test.go

Adding some quick unit tests to check that:
- Manifest generation and serialization doesn't fail with valid configs.
- Manifest generation fails with expected errors with invalid configs.
- Manifest serialization fails with expected errors with invalid resolved sources.
- Serialized manifests contain expected stages.
These are quite basic and don't cover anything that wouldn't be caught by our more comprehensive integration tests, but are useful for catching regressions quickly (especially for rapid iteration during development).

Manifest generation unit tests

---

Containerfile
bib/cmd/bootc-image-builder/main.go
devel/Containerfile
entrypoint.sh

This is prep for adding multiple entrypoints; right now the Go code has a `build` verb that is always injected by this wrapper.
Move the default values into the Go code.
A future change will likely make things so that users are required to pass `build` (or perhaps `build-disk`) and this shell script goes away entirely.

Drain logic from entrypoint into Go code

---

bib/cmd/bootc-image-builder/partition_tables.go

See https://github.com/containers/bootc/pull/294
This is particularly motivated by https://github.com/CentOS/centos-bootc-dev/pull/27 because with that suddenly `dnf` will appear to start working but trying to do anything involving the kernel (i.e. mutating `/boot`) will end in sadness, and this puts a stop to that.
(This also relates of course to ye olde https://github.com/osbuild/bootc-image-builder/issues/18
where we want the partitioning setup in the default case
to come from the container)

Mount /boot ro by default

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
test/test_build.py
test/testcases.py

This PR just renames the `iso` artifact to `anaconda-iso`.
The reason is that I would like to potentially introduce a *different* generic "live iso" that generates *exactly the input container* just as a Live ISO, very similar to how Fedora CoreOS (and one of its parents, the original Container Linux) do it.
This (proposed) `live-iso` would have several use cases, such as always running from a PXE boot.  I also think this is the long term architecture for an ISO, as opposed to the current Anaconda.  It would also be the same as how e.g. Fedora Workstation does it, where the installer is just an app in the system.
Anyways again, this is just a rename.  For compatibility we continue to honor the `iso` as an alias.

Rename `iso` -> `anaconda-iso`

---

bib/cmd/bootc-image-builder/main.go
bib/go.mod
bib/go.sum

When not doing a cross arch build use the same resolver as host and target arch are the same.
This addresses the comment in https://github.com/osbuild/bootc-image-builder/pull/139#discussion_r1479679146

bib: avoid duplicating resolvers

---

bib/cmd/bootc-image-builder/cloud.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/upload/main.go
bib/internal/uploader/aws.go

There is a bug in the bib code right now that when uploading the AMI. It assume that the images are always build for the host architecture. But bib supports building/uploading cross-architecture images too.
Thanks to Ondrej for spotting this.
[this really should have a test but we need this urgently, I will try to write one after]

bib: support uploading to `--target-arch` as well

---

devel/Troubleshooting.md
devel/bootc-install

Add a troubleshooting guide and a script that builds an image from a bootable container using `bootc install to-disk`, effectively removing BIB from the pipeline.  The guide and script are meant for investigating build or boot issues when it's not clear if the source of the issue is BIB, or something in the bootable container itself.
I'd like for the troubleshooting guide to be extended with more information about what users can try to investigate or work around failures.  We could also later link to https://gitlab.com/bootc-org/podman-bootc-cli with information on how to use it for debugging.
I initially considered linking to the guide from an issue template on GitHub but I think for now we can keep it here and link to it when we want more information from users reporting issues. …

Add troubleshooting guide

---

test/test_build.py

This commit disabled the anaconda-install test that fails currently because of https://github.com/osbuild/bootc-image-builder/issues/233
[resurrecting https://github.com/osbuild/bootc-image-builder/pull/234 as https://github.com/osbuild/bootc-image-builder/pull/231 seems to need more work]

test: disable anaconda-iso test because of issue#233

---

bib/internal/setup/setup.go

This ensures that the new `partscan` feature in osbuild works. By default the containers only have a static snapshot of /dev on a tmpfs. This means that anything later added by losetup will be missing inside the container.
It also means that https://github.com/osbuild/osbuild/pull/1468 can be reverted.
This should unblock https://github.com/osbuild/bootc-image-builder/pull/120 and also https://github.com/osbuild/images/pull/462

bib: mount `devtmpfs` inside the container too

---

bib/cmd/bootc-image-builder/main.go
bib/internal/setup/setup.go

The way osbuild works is to synthesize a filesystem tree in the store, then copy it to the disk.  This ensures the label for the store is `root_t` which ends up being the labeling for the "infrastructure" bits in the `/ostree` repository in the target root.
This in turn is blocking a lot of things.
Closes: https://github.com/osbuild/bootc-image-builder/issues/149

Ensure root_t label for /store

---

README.md
bib/cmd/bootc-image-builder/main.go
bib/go.mod
pytest.ini
test/test_build.py
test/test_manifest.py
test/testcases.py

When producting a disk image, I want to be able to specify multiple at the same time. This would speed up builds and allow creating of an AMI, ISO and qcow2 all in one run.

Allow users to specify multiple types

---

.github/workflows/tests.yml

Similar to the osbuild PR#1636 this comit cancels CI runs for PRs that got updated.
This changes the behavior in a way that whenever a PR gets updated all still-in-progress runs get canceled and new runs get spawned.

workflow: cancel in-progress tests on PR updates (HMS-3697)

---

test/containerbuild.py
test/test_opts.py

This also adds some infrastructure to fake the actual osbuild run which is potentially useful in the future as well.

test: add integration tests for new --chown feature

---

Containerfile
README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
build.sh
plans/all.fmf
test/test_build.py
test/testcases.py

Enable the ability to use local containers from containers-storage rather than pulling containers from a remote registry.

main: enable containers-storage (HMS-3235)

---

bib/cmd/bootc-image-builder/build_type.go
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/bootc-image-builder/main_test.go
bib/go.mod
bib/go.sum

_Requires osbuild/images#512_
The bootc-disk image manifest now always contains all pipelines needed to generate all image types. This way we can build any combination of disk images depending on what we need to export without needing to conditionally add or remove pipelines.
Set the filename as just "disk" since extensions are added automatically for each file.

Use the all-manifest for disk image builds

---

test/test_build.py
test/testcases.py

The vmdk images cannot be booted easily in qemu so we will just
check that the image is there but do no functional testing.
This is a followup for https://github.com/osbuild/bootc-image-builder/pull/251

test: add test that ensures "vmdk" images are build (HMS-3758)

---

bib/internal/uploader/aws_test.go

The length of the progress bar depends on the terminal width so let's make the test matching flexible.

uploader: test the progress upload output with a regex

---

Makefile
devel/Containerfile.hack

Two conveniences:
- I commonly work on multiple projects in multiple languages and I find it very useful to have typing `make` do something useful by default.
- This `Containerfile.hack` I found is a lot faster and more understandable for the case of just wanting to hack on the Go code including changes to osbuild/images versus what is in `devel/Containerfile` which is much more heavyweight and assumes we're also hacking on osbuild.

devel: Add Makefile and Containerfile.hack

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
test/test_build.py
test/test_manifest.py

This pull request switches to using containers-storage even without the --local flag.

Switch to using containers-storage even without --local

---

.dockerignore
devel/Containerfile.hack

It's best practice to trim out stuff we don't need in the container build from the context directory; this way if I e.g. edit `tests` it won't invalidate the build caches.
Similarly, it's a really good idea to exclude things like `bin/` from the builds - you don't want to accidentally somehow be using incorrect cached *final* binaries.
But `Containerfile.hack` is all about bypassing that, so add a comment for why we use the bind mount.

build: Add .dockerignore and a comment

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

This reverts commit b066c06ebbcc7107d778f6ceff343517b6b9a5c4.
This commit could have broken the release pipeline, so let's try reverting it, and see if it helps.

Revert "chore(deps): update rhtap references"

---

Containerfile

6e965d2413f7bdc8844bf09c9c9968c6c170d96d changed bib to always go
through a container storage. However, if the container runtime running
bib was using overlayfs (the default), we ended up in a situation that
/var/lib/containers/storage was overlayfs. When bib itself tried to
worked with these containers, it called podman/skopeo that tried to
create overlayfs inside overlayfs, which is a forbidden combination.
This worked by accident with centos-boocs/fedora and centos containers,
because they contain fuse-overlayfs, and podman/skopeo apparently
silently switched to using fuse. This isn't only slow, but it also
didn't work with container images without fuse-overlayfs. One example
of such an image is the iot-bootable-container. E.g. …

bib: make /var/lib/containers/storage a volume

---

.github/workflows/tests.yml

During the test of PR#291 we got a failure that should get fixed by moving to a newer podman.

workflow: move to podman 4 in the tests

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

This supports the building of source containers.
We want to enable the "hermetic" parameter also, but since rpm content is being installed that won't be possible until
https://issues.redhat.com/browse/KONFLUX-1318 completes.

build: Enable prefetch of go deps in konflux pipeline

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
bib/internal/setup/setup.go
test/containerbuild.py
test/test_manifest.py

As a starting point for the image size we use the container size and just double it.

main: double container size as the min size of "/" (HMS-3810)

---

bib/cmd/bootc-image-builder/main.go
bib/internal/setup/setup.go
test/test_manifest.py

Ensure to error early when the user is not passing the required
```
-v /var/lib/containers/storage:/var/lib/containers/storage
```
when doing a local build.
[edit: I looked again and the loop is so simple that I feel the integration test is enough]

bib: check /var/lib/containers/storage when using "--local" (HMS-3792)

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

This reverts commit dfdc210238f7f6c2b6c2dd06ed0ace8246b11da3.
Since this commit, all Konflux pipelines are failing. Let's try
reverting it to see if it fixes the issue.
cc @ralphbean

Revert "build: Enable prefetch of go deps in konflux pipeline"

---

.github/workflows/tests.yml

The tests are broken for weeks, probably due to broken podman store
on our macos runner. This already happened in the past and it always
requires a manual intervention to fix it.
Since we don't think that these tests provide much value over what
we are already testing on Linux in GitHub Actions and in Testing Farm,
let's disable them.

github: disable tests on macos

---

bib/go.mod

I think pinning on 1.19 is holding some dependency updates back, and 1.20 is in rhel9 now.

Update to go 1.20

---

bib/internal/setup/export_test.go
bib/internal/setup/setup.go
bib/internal/setup/setup_test.go

When the container storage is checked it may come from a btrfs subvolume. In /proc/self/mountinfo this looks like:
```
1364 1345 0:33 /root/var/lib/containers/storage /var/lib/containers/storage rw,relatime - btrfs /dev/mapper/luks-1356123c-c7b9-1bd7-a8bf-e13d4cbb5500 rw,seclabel,compress=zstd:1,ssd,discard=async,space_cache,subvolid=257,subvol=/root
```
as a quick fix just compare the suffix of the root instead of the full path.
Thanks for Ondrej!
[I want to write a test but I also want to unblock Ondrej]

setup: deal with btrfs subvolumes when checking mapped storage

---

.gitignore
Containerfile
Makefile
bib/cmd/bootc-image-builder/main.go

Check AWS S3 bucket and permission before starting the build.
Resolves #220 
PR https://github.com/osbuild/images/pull/539 needs to be merged & deployed **before**

main: check s3 bucket access before starting (HMS-3099)

---

bib/cmd/bootc-image-builder/main.go

cmdBuild is already relatively long so extract the helper to handle the AWS cmdline
This also move to use logrus in the helper, I am sitting on the fence a bit if this should be a info or a debug, it seems if this is a slow check, maybe Info() is better as it is visible by default (AIUI).

bib: extract handleAWSFlags() helper

---

Containerfile
package-requires.txt

[pin osbuild to a version before the depsolver changes](https://github.com/osbuild/bootc-image-builder/commit/6fddc67a7b308f440e02b288c9bbe8bd001071c0)
https://github.com/osbuild/osbuild/pull/1674 broke the depsolver API.
This is already fixed in images, but bumping images in bib requires
more changes, and we want to unblock everything ASAP, so let's just
pin osbuild to get the old depsolver once again.
Fixes #352
---
[Containerfile: remove outdated rpm-ostree upgrade](https://github.com/osbuild/bootc-image-builder/commit/4796bc0988dcbc15bd0d71deab0f7839f57e770b)
I'm getting the following error, so this is no longer needed:
The same or higher version of rpm-ostree is already installed, cannot update it.

pin osbuild to a version before the depsolver changes

---

README.md
test/test_build.py

I noticed this was wired up in the code, but undocumented and untested.
There are valid use cases for machine-specific kernel arguments, so let's support that here.
(What's the best place to verify that the kargs show up in the test
VMs? )

document that `customizations.kernel.append` exists

---

test/test_build.py

Now that we always pull the containers this may speed up things when layers are found in the container storage.
I finally measured this, at least locally it has a noticable effect. I tested a single run of 
```
$ sudo pytest -s -vv './test/test_build.py::test_image_boots[quay.io/centos-bootc/centos-bootc:stream9,raw]'
```
- with the patch a single test run  takes `2:39min` on my system
- without `4:40min`

test: map /var/lib/containers/storage when running bib

---

test/test_build.py

Small followup for https://github.com/osbuild/bootc-image-builder/pull/351 where Colins pointed out that we currently do not test the customizations for the kernel commandline arguments.

test: test that kernel commandline args are passed correctly

---

README.md
bib/cmd/bootc-image-builder/main.go
test/test_build.py

When passing a config, it's an ergonomic hit to need to provide it on *both* the `podman run` invocation *and* the arguments to the binary.
Change things so that we automatically pick up `/config.json` if it exists in the container.  This way the user only needs to give the podman argument.

Automatically pick up `/config.json` if it exists

---

bib/cmd/bootc-image-builder/main.go
test/test_manifest.py

We recently had a bugreport where a panic had very little error context:
```
Generating manifest manifest-iso.json
panic: exec: no command
```
this prompted this commit so that:
a) we do add more context to our errors
b) avoid panicing when we can also return errors
This may lead to some stuttering `cannot do foo: cannot generate foo: cannot make foo a thing` but we can tweak and more context right now is probably better than less (ideally we would have tests that cover this and help us figure out how to fine tune it).

main: decorate more errors with context and avoid panics

---

.github/workflows/tests.yml
bib/cmd/bootc-image-builder/main_test.go

Previously the `0` value of the images `arch.Architecture` iota
was of type `ARCH_AARCH64`. However with
https://github.com/osbuild/images/commit/05355326188f3d2ad49003784d681524eba466ce
this is no longer the case an the zero type is now a proper
`UNSET` type. And the tests now fail because they did not set
the architecture.
This PR fixes this by setting the architecture and also adds them to the GH action

bib: run go unittest in GH actions and fix them

---

bib/cmd/bootc-image-builder/main.go
test/containerbuild.py
test/test_opts.py

If the user passes `--target-arch` and it is the same as the current arch just ignore the option as this is the default behavior anyway.
This partly closes
https://github.com/osbuild/bootc-image-builder/issues/316

bib: ignore --target-arch if it is the same as the running arch

---

bib/cmd/bootc-image-builder/main.go
bib/internal/util/util.go
bib/internal/util/util_test.go

Subject: [PATCH] bib: simplify getContainerSize()
The getContainerSize() was not using some of the modern go helpers.
So let's use `exec.Command().Output()` and introduce a new
`util.OutputErr()` helper that will be able to also show stderr to
the user if the Output() call returns an error.
---
Subject: [PATCH] bib: show error details from podman if `podman pull` fails
Right now if `podman pull` fails no error output from podman is
visible to the user. This commit tweaks that so that the output
is part of the error.

bib: tweak podman pull/getContainerSize

---

bib/cmd/bootc-image-builder/image.go

It turns out that on centos9 users are not added when specified in kickstart files. This commit should fix this and users are added. I did a manual validation but this will be part of the test for https://github.com/osbuild/bootc-image-builder/pull/338 (the test in 338 still not works, it seems the machine has no network(?) but I guess baby steps :)
P.S. No test as this really needs to be in images and I will add a test there (and then this needs reverting).

image: enable `org.fedoraproject.Anaconda.Modules.Users` if needed

---

.github/workflows/tests.yml

On GH runners /mnt has 70G free space and because we ran out of diskspace in https://github.com/osbuild/bootc-image-builder/pull/338 in what appears the container storage move the container storage via a bind mount to `/mnt/var/lib/containers`.

github: put `/var/lib/containers` on `/mnt` via bind mount

---

bib/cmd/bootc-image-builder/image.go
bib/go.mod
bib/go.sum

This will use the new features from:
https://github.com/osbuild/images/pull/614
and
https://github.com/osbuild/images/pull/616
To enable kernel parameters in the target system and also to enable network on boot.
Tests will be done via https://github.com/osbuild/bootc-image-builder/files/15027014/0001-test-enable-iso-installer-tests-for-both-centos-fedo.patch.txt

bib: enable kernel options and network on boot in ISO installer

---

.github/workflows/tests.yml
test/test_build.py

This hopefully speeds up the tests, especially the iso ones.
In my local testing the different between first run (no shared cache) and second run (cache populated):
```
$ sudo pytest  -s -vv  './test/test_build.py::test_iso_installs[quay.io/centos-bootc/centos-bootc:stream9,anaconda-iso]'
no cache
=================== 1 passed, 1 warning in 616.89s (0:10:16) ===================
second run with populated cache
=================== 1 passed, 1 warning in 393.41s (0:06:33) ===================
```

workflow,tests: use `/var/tmp/osbuild-test-store` and cache that

---

test/test_build.py
test/testcases.py

Now that we can inspect the image enable the iso installer tests again.

test: enable iso installer tests for both centos/fedora

---

test/test_build.py

This breaks the tests running locally and in Testing Farm.
This issue was introduced in #375.

test: Make sure that the osbuild store exists

---

bib/cmd/bootc-image-builder/main.go
test/containerbuild.py
test/test_opts.py

When switching to always leveraging the local storage, I forgot to pass
the --tls-verify flag. This commit fixes it.
@mvo5 any ideas how to test this?

Fix passing the --tls-verify flag to podman pull

---

README.md

A while ago there was PR#17 that emphasised centos stream9 instead of fedora:eln. We could not take it back then because the iso installer was not quite ready for centos and there were hardcoded EFI names. But now everything is in place so this cherry picks the original changes from Colin.
See also https://github.com/osbuild/bootc-image-builder/pull/17

README.md: target c9s because ELN is more aggressive and has bugs

---

bib/internal/container/container.go
bib/internal/container/container_test.go

This commit fixes a nil pointer exception when `Container.New()` needs to run the defer that calls c.Stop(). The semantics of named returns are subtle here. The local var `c` is non-nil. However when `New()` returns with `return nil, err` (e.g. in line 64+) then `c` becomes `nil` (because the of return nil). Which means the defer now tries to use a `nil` pointer and crashes.
The fix is to either use `naked` returns everywhere or just remove the named returns. The later seems more in line with what we (and the go community) generally do.
A regression test is added too.

container: fix crash when `Container.New()` defer() is run

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/bootc-image-builder/main_test.go
bib/go.mod
bib/go.sum
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go
bib/internal/buildconfig/export_test.go
test/test_manifest.py

This commit adds support to load blueprints from toml as well.
[draft as tests are missing]

bib: allow blueprints in toml as well

---

bib/go.mod
bib/go.sum

Bump `osbuild/images` to v0.57.0. This should unblock the ability to build cross-arch images with manifest lists from local storage.

bib: bump images lib for local manifest lists

---

bib/cmd/bootc-image-builder/main.go
bib/go.mod
bib/go.sum
test/test_manifest.py

In the more complex world of the manifest lists the native target arch check of bib does no longer work. Rely on the resolver to give us the right architecture.
Thanks to Charlie Drage for reporting the issue.
See also https://github.com/osbuild/images/pull/595 and https://github.com/osbuild/images/pull/635

bib: tweak target arch check

---

test/test_opts.py

Trivial test that ensures that the `--log-level` is honored from
the commandline. Uses the fake_container with an empty osbuild
so it is reasonable fast (about 20s on my system).

test: add smoke test that checks that --log-level is honored

---

bib/internal/container/container.go

For the generic Fedora base image the current plan is we won't include a default rootfs; that will be up to derived containers.
Output a slightly more useful error message in this case.

Provide better error for containers without a rootfs default

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main_test.go
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go
test/test_build.py
test/test_manifest.py

Make the buildconfig a blueprint but keep support for the legacy
format for now.
[build on top of https://github.com/osbuild/bootc-image-builder/pull/392]

buildconfig: make buildconfig blueprint compatible and  support legacy

---

README.md
bib/cmd/bootc-image-builder/main.go
test/test_manifest.py

Some container images don't have a default filesystem type. In this
case, a disk image build will fail. I'm a strong believer that we need
a one-line command to build a disk image. Thus, this commit adds
--rootfs which sets the root filesystem type if the container image
doesn't have one (or overrides it if it has one). By using --rootfs,
users will be able to run just one command to build an image once
again.
In the future, we will support custom partitioning via blueprints (or
different format). This means that we will need to figure out what takes
precedence. However, I suggest to cross that bridge when we get there.

bib: add --roofs to be able to select the root fs type

---

Containerfile
bib/cmd/bootc-image-builder/main.go
bib/cmd/cross-arch/canary.go
bib/internal/setup/export_test.go
bib/internal/setup/setup.go
bib/internal/setup/setup_test.go
build.sh

This commit checks early if cross architecture building support via `qemu-user-static` (or similar tooling) is missing and errors in a more user friendly way.
[draft as it needs some proper tests still]

bib: detect missing qemu-user early

---

test/test_build.py

Small fix to the `image_type` fixture by deduplicating the call to `build_images`

test: minor fix to image_type fixture

---

README.md

- Link upstream docs, as there's a lot more there around things like building container images, etc.
- Switch to using `--local` by default because it avoids foot-guns around images which require authentication, which we expect to be common in general

README.md: Link upstream docs, default to --local

---

plans/all.fmf

Testing farm was broken for a while, it seems we got the wrong disksize for unkown reasons. This is now fixed by switching to a different disk request syntax.
Closes: https://github.com/osbuild/bootc-image-builder/issues/401

tmt: fix testing farm test execution

---

test/test_build.py
test/vm.py

A continuation of https://github.com/osbuild/bootc-image-builder/pull/357 - the root user is used to do a `bootc status` inside the booted container to ensure the setup is correct. This is nicer then the previous `sudo` approach and it has the added benefit of testing the root user creation/setup during the build too.

test: test root user setup

---

.github/workflows/tests.yml

When a merge queue runs it will update the cache in the context of `merge_group`, not `main` [0] - this means that the cache cannot be restored by future PRs and because of the restrictions for caches [1] we currently have no caching.
This is attempt to "fix" this. It sucks a bit because the tests that are run as part of the merge queue will be run again when "main" is updated just so that the cache gets populated. So maybe it's not worth it but right, we need to measure. Either it's this or we can remove the cache action as it is not working right now.
[0] https://github.com/orgs/community/discussions/66430
[1] https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

workflow: run tests on "push" to "main" to populate cache

---

README.md
bib/cmd/bootc-image-builder/main.go
test/test_opts.py

With the default to pick up the config from `/config.{toml,json}` nowdays the `--config` flag is not very useful anymore. It is actually confusing users as they may hink they to pass two config arguments into the container.
So this commit removes `--config` from the README and hides it in bib. It is not removed entirely for two reasons:
1. backward compatibility with existing scripts
2. it is useful for developers to run
```
$ sudo ./bootc-image-builder manifest --config local-config.json
```
to get a manifest from outside a container for debugging purposes (but it's not a strong reason).

README,bib: hide `--config` from users, remove from docs

---

bib/cmd/bootc-image-builder/export_test.go
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
test/test_build.py
test/test_manifest.py

Really simple change :) The testing feels a bit klunky, suggestions welcome. I thought about checking the manifest, but it boots the image anyway so checking the output of `df` seemed to be the most straight forward way.

Hook up blueprint filesystem customizations

---

README.md

As suggested by Charlie (thanks!) this commit adds a description and link to the podman desktop bootc extension.
Closes: https://github.com/osbuild/bootc-image-builder/issues/449

README: mention/link to bootc podman desktop extension

---

bib/cmd/bootc-image-builder/image.go
bib/go.mod
bib/go.sum
bib/internal/source/source.go
bib/internal/source/source_test.go
test/test_build.py
test/test_manifest.py
test/testcases.py

We currently cannot build Fedora 40 ISO because we require lorax-templates-rhel everywhere. Let's parametrize it based on the distribution. Also, let's add Fedora 40 tests.
Fixes #421

Fix ISO for Fedora 40 and add Fedora 40 CI

---

bib/cmd/bootc-image-builder/main.go
bib/internal/container/container.go
bib/internal/container/container_test.go

Tweak the error output when a bootc container does not contain a default filesystem. The new error will hint what commandline option to use. The error message generation is also moved from the helper into the main program because only the main.go knows what options it supports.
The error is now:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
Error: cannot generate manifest: no default root filesystem type specified in container, please use "--rootfs" to set manually
2024/06/24 11:39:39 error: cannot generate manifest: no default root filesystem type specified in container, please use "--rootfs" to set manually
```

bib: improve error when a container does not contain a default rootfs

---

HACKING.md

As pointed out in https://github.com/osbuild/bootc-image-builder/pull/479 we are currently lacking a HACKING.md or similar to explain how to run our tests. As this is non-obvious this commit adds a new `HACKING.md` with the information.
It's a bit bare-bone and it would also be nice to create something like a `get-test-deps.sh` or similar helper that is then used in our various GH/tmt actions and can also be used by the user to get up-to-date test dependencies. But that is something for a followup :)

docs: add new HACKING.md

---

bib/cmd/bootc-image-builder/main.go
test/test_opts.py

We handle the errors ourselfs in bootc-image-builder but there was a setting missing which lead to double prints:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
Error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
2024/06/24 10:26:42 error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
```
This commit fixes this and adds a test:
```
$ go build && sudo ./bootc-image-builder manifest quay.io/fedora/fedora-bootc:40
2024/06/24 10:43:38 error: cannot generate manifest: cannot get rootfs type for container: container does not include a default root filesystem type
```

main: set `SilenceErrors` to avoid double error printing

---

bib/cmd/bootc-image-builder/main.go

The error when running without a valid container looks like this:
```
$ go build && sudo ./bootc-image-builder manifest no-such-thing
2024/06/24 11:19:29 error: cannot generate manifest: failed to pull container image: exit status 125
Error: short-name "no-such-thing" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```
right now. The second error and the first are a bit diconnected but in fact the second is the output from the failed pull command. So this trivial PR changes the error to use `util.OutputError` instead which makes clearer where the second line comes from:
```
$ go build && sudo ./bootc-image-builder manifest no-such-thing
2024/06/24 11:33:26 error: cannot generate manifest: failed to pull container image: …
```

bib: use `util.OutputErr()` in manifestFromCobra()

---

Containerfile
bib/cmd/bootc-image-builder/main.go
test/test_opts.py

For easier tracing of what revision was used by who this commit adds the git revision to the main `bootc-image-builder` binary.
To do this we need to include the git tree in the build container, this should be enough but for some reason, see bib issue#511 the build-in `go build` vcs info is not picked up. So this includes a workaround to manually stamp the revision.
[edit: this should help with questions like https://github.com/osbuild/bootc-image-builder/pull/489#issuecomment-2197787396 - ie make it trivial to see what git revision the user is using)]

build: include git revision in main "bootc-image-binary"

---

README.md
bib/cmd/bootc-image-builder/image.go
test/test_manifest.py

See https://github.com/osbuild/images/pull/631

Add support for arbitrary kickstart file injection into ISOs (HMS-3879)

---

test/test_manifest.py
test/test_opts.py

The usage of `--entrypoint` was a bit all over the place. This commit unifies it so that if the entrypoint is not "build" we always pass `--entrypoint=/usr/bin/bootc-image-builder` and the the arguments to bib are passed after the container.
This makes test (hopefully) more readable.

test: unify how `--entrypoint=` is used

---

bib/cmd/bootc-image-builder/main.go
bib/internal/setup/setup.go
bib/internal/setup/setup_test.go
test/test_manifest.py

This is my first attempted commit to this project.
I'm still learning the repo structure and dev workflow. Few questions on testing.
1. In this commit I'm relying on having images locally. I didn't see anything similar so I assume we want to avoid this/tests will fail. Is there an alternative?
2. If I have to rely on testing by hand, how can I use local changes? I'm thinking I just  https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file# building and then can  follow examples?
Closes: https://github.com/osbuild/bootc-image-builder/issues/380

bib/internal/setup: Tag validate early

---

test/conftest.py
test/test_build.py
test/test_manifest.py
test/testcases.py

The old way of generating test cases was via strings that would use a `,` to differenciate between various parameters like container_ref or image_type.
With the adding of the rootfs this becomes unwieldy (arguable it was unwieldy already and now it's unentable). This commit introduces a proper "TestCase" class that makes generating and reading the test cases a lot eaiser (IMHO).
Note that this was prompted because of PR#439 where we want to make the rootfs tests on fedora "btrfs".
[draft until tests are green, there is a lot of churn in here :)]

test: rework how test cases are represented/generated

---

bib/cmd/bootc-image-builder/main.go
test/test_opts.py

It can be useful to run `bootc-image-builder` outside a container, e.g. during local development. Let's allow it but warn the user that it's not a supported configuration.
[my main use-case is to run the experimental progress bar as it's hard to automatically test]

main: allow running outside of a container

---

README.md

The example in the README does not actually work and needs a `customizations` key. Thanks to Charlie Drage for finding this!
Closes: https://github.com/osbuild/bootc-image-builder/issues/534

README.md: fix user customisations example

---

bib/cmd/bootc-image-builder/image.go

**bib: enable Anaconda Users module for ISO**
We generally only enable the Users module in ISOs when a user is
configured because we want the installation to be fully automatic /
unattended and, in the general case, Anaconda will block and wait for
user input if no users are configured.  However, since we always add
`rootpw --lock` to our kickstart file, this satisfies Anaconda's user
configuration rule and the installation proceeds without blocking.
Enabling the Users module unconditionally allows users to include user
configuration when they inject their own kickstart files.
---
**bib: enable Anaconda Services and Security modules**
These modules don't affect any existing functionality but enable more
kickstart verbs for users that want to use them.
---

Enable new Anaconda modules: Users, Services, and Security (RHEL-49499)

---

.tekton/bootc-image-builder-push.yaml

This is needed in order to migrate to 0.4, we somehow did the change
only in the pull request pipeline.

konflux: add missing deprecated-base-image-check params

---

package-requires.txt

Konflux mounts in /etc/pki/entitlement instead of /run/secrets. This is not how we intended bib to work, but it works if subscription-manager is in bib. Include it temporarily, before we find a better long-term solution.
See https://github.com/konflux-ci/build-definitions/blob/f3ac40bbc0230eccb8d98a4d54dabd55a4943c5d/task/build-vm-image/0.1/build-vm-image.yaml#L198

include subscription-manager to fix integration with Konflux

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/partition_tables.go

This patch adds support for s390x platform and its disk partition table layout.

bib: Add support for s390x architecture

---

bib/go.mod
bib/go.sum
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go

This pull request includes two changes. First, it switches from `pelletier/go-toml` to `BurntSushi/toml` in the `bib` module. This change removes a dependency and aligns with the use of `BurntSushi` elsewhere in the codebase. Second, it adds error handling for unknown toml keys in the `buildconfig` module. This change improves clarity and prevents confusion when using older versions of `bib` with recent customizations.

Switch to BurntSushi/toml and error out on unknown toml keys

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/partition_tables.go

bootc-image-builder lacks support for ppc64le.
This two patch series adds such support.
- Update manifestForDiskImage to include support for ppc64le architecture
- Update partition table map with ppc64le specific data
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

Add support for ppc64le architecture

---

bib/internal/buildconfig/config_test.go

When moving to the new toml reader the
TestReadUserConfigErrorWrongFormat test broke. This trival commit fixes it.
C.f. https://github.com/osbuild/bootc-image-builder/pull/549

bib: fix unit test for TestReadUserConfigErrorWrongFormat

---

test/test_manifest.py
test/testcases.py

The new `test_manifest_target_arch_smoke` test ensures that for
all supported `--target-arch` architecture bib can create a
manifest. No further functional testing (like building or booting)
is done.
[draft as it needs https://github.com/osbuild/bootc-image-builder/pull/497 and a container ref for a s390x bootc container and also potentially should only be merged once the bootc images for ppc64le, s390x are on a more offical place]

test: add new `test_manifest_target_arch_smoke` test

---

test/test_build.py
test/test_manifest.py
test/testcases.py

Make the testcases generation more readable introduce new
dataclasss for `TestCase{Centos,Fedora}` so that the testcases
just become something like:
```python
if what == "ami-boot":
return [TestCaseCentos(image="ami"), TestCaseFedora(image="ami")]
```
[draft because it needs https://github.com/osbuild/bootc-image-builder/pull/526 first]

test: introduce new `TestCase{Centos,Fedora}` classes

---

README.md

With https://github.com/osbuild/bootc-image-builder/pull/439 merged we can now build btrfs images (for systems that support this).
Make sure this is mentioned in the README.
Fixes: https://github.com/osbuild/bootc-image-builder/issues/541

README: mention `--rootfs btrfs`

---

bib/cmd/bootc-image-builder/main.go
test/test_manifest.py

The ISO build doesn't require the rootfs configuration from the image,
so there is no need to read it from the container nor to require the
flag when it is missing.
Closes #494.

Skip rootfs handling when building ISOs

---

bib/cmd/bootc-image-builder/partition_tables.go

Closes: https://github.com/osbuild/bootc-image-builder/issues/551
There was a fair amount of copy-paste even when we just had aarch64+x86_64, the addition of duplicate bootfs/rootfs definitions for ppc64le+s390x is a strong motivation to finally define shared constants.
I also factored out a shared `const` with some comments for the disk UUID that will save someone some time wondering about it later (this textually but not logically conflicts with https://github.com/osbuild/bootc-image-builder/pull/568 but I think this makes sense to land first).

partitions: Switch aarch64 to GPT, fully deduplicate

---

README.md

Also include hint about how to use `bootc-image-builder version` so that users can report what version they are using.

README: include short section on reporting bugs

---

bib/go.mod
bib/go.sum

This PR updates the indirect docker/docker dependency to v26.1.5 to mitigate CVE GHSA-v23v-6jw2-98fq.
According to https://github.com/moby/moby/issues/48269, there is a mistake in the patched version info for the CVE.  v26.1.4 is affected, while v26.1.5 is not.

go.mod: update docker/docker to v26.1.5

---

test/test_build.py
test/test_manifest.py
test/testutil.py

This consolidates the duplication from `test_{build,manifest}` when running podman. All common arguments are now in a single place which also means that the host container storage is mapped consistently which should speed up the tests.

test: extract `testutil.podman_run_common`

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

PR #558 was merged without updating the configurations according to the migration notes, which broke the konflux pipelines.
See also
- https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
- https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-remote/0.2/MIGRATION.md

tekton: drop references to BASE_IMAGE_DIGESTS

---

Containerfile
bib/cmd/bootc-image-builder/main.go
test/test_opts.py

When `tmt` runs it will not include the `.git` dir when it prepares
the source. This was breaking the tmt tests. This commit just makes
the containerfile copy the entire current working dir so that we
get `.git` if it's there or it is skipped otherwise.
Closes: https://github.com/osbuild/bootc-image-builder/issues/583

Containerfile: copy the entire "." dir into /build

---

bib/go.mod
bib/go.sum

Backported version of 78455be693520f8cc4a3bc51262ea69613664603
See also https://github.com/osbuild/bootc-image-builder/pull/587

[rhel-9.4.0] go.mod: update docker/docker to v26.1.5

---

README.md
bib/cmd/bootc-image-builder/image.go
test/test_manifest.py

**bib: use anaconda package constants for module names**
---
**bib: enable customizing anaconda modules**
Connect the blueprint customization to the module configuration (enabled
and disabled) in the pipeline.
---
**README: document the new customizations.installer.modules options**
Based on the upstream blueprint documentation:
https://github.com/osbuild/osbuild.github.io/pull/100
---

Support configuring Anaconda modules for ISOs

---

bib/data/defs/fedora-41.yaml
bib/internal/distrodef/distrodef.go
bib/internal/distrodef/distrodef_test.go

This adds a fallback when no extact match for a distrodef is found.
The rules are:
- exact match (e.g. fedora-40) wins
- highest version for the given distro wins otherwise, e.g.
fedora-42 is returned when asking for fedora-44 and [fedora-39 fedora-42]
are available
- it is an error if the requested version is smaller than the availalble
version and there is no exact match. E.g.
an error is raised if asking for fedora-38 and [fedora-39 fedora-42]
are available
Build on top of https://github.com/osbuild/bootc-image-builder/pull/573

distrodef: add fallback code when extact distro ver is not  found

---

Containerfile
README.md
bib/cmd/bootc-image-builder/main.go
devel/Containerfile
entrypoint.sh
test/test_manifest.py
test/test_opts.py

Prior this commit, the bootc-image-builder container image had
a custom entrypoint that hardcoded the use of the build subcommand. This
meant that if a user wanted to use a different subcommand, they had to
overwrite the entrypoint.
This commit changes the cobra code in bib to fallback to build if no
subcommand was given. This is slighly ugly, but it allows us to remove
the custom entrypoint, streamlining the use of subcommands. Let's see
an example of calling the version subcommand:
Before:
podman run --rm -it --entrypoint=/usr/bin/bootc-image-builder \
quay.io/centos-bootc/bootc-image-builder:latest version
After:
sudo podman run --rm -it \
quay.io/centos-bootc/bootc-image-builder:latest version
Kudos to https://github.com/IKukhta for his code from …

bib: make build the default subcommand

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
bib/go.mod
bib/go.sum
test/test_manifest.py

Two changes:
- The pathpolicy.PathTri type is no longer exported and it is `pathpolicy.Pathpolicies` instead [0]
- The error messages from images for path policy violations changes and need an update (arguable this is not the best layer to test the error  details here and instead we should check how much we can move down to images but that is a followup :)
[0] https://github.com/osbuild/images/pull/854

bib: update to images v0.78 and update for API changes

---

bib/go.mod

Downstream builds are failing with
```
2024-08-21 10:48:13,320 ERROR PackageManagerError: Required/recommended Go toolchain version '1.22.6' is not supported yet.
Error: PackageManagerError: Required/recommended Go toolchain version '1.22.6' is not supported yet.
Please lower your required/recommended Go version and retry the request. You may also want to open a feature request on adding support for this version.
```
The toolchain line isn't a requirement in go.mod, so let's drop it.

go.mod: drop 'toolchain go1.22.6'

---

bib/cmd/bootc-image-builder/export_test.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/bootc-image-builder/main_test.go

[draft as this needs tests]
In PR#608 we dropped the container entrypoint and moved the logic to detect what command to run into the cobra parsing.
However it seems certain situations like:
```
bootc-image-builder  --type qcow2 --tls-verify=true  --local quay.io/centos-bootc/centos-bootc:stream10
```
are not detected correctly (thanka to Chunfu Wen for reporting!).
This commit detect this usage and injects the build arg then too.
Closes https://github.com/osbuild/bootc-image-builder/issues/614

bib: fix injecting default "build" arg into root for flags like --local

---

test/testcases.py

Unfortunately ostree is now using openat2 which is currently not supported by qemu-user so the cross-arch install fails. We are looking into this but for now disable the test to unblock other landing as there is nothing bib can do to fix this.

test: disable arm64 test until #691 is fixed

---

bib/data/defs/centos-10.yaml

Following the excellent work of Tomáš in [0] this commit updates the distro dependencies for centos10/rhel10 to include `anaconda-install-img-deps` which is what is required to get a working anaconda environment.
This with the new osbuild and the fix in [1] should fix https://github.com/osbuild/bootc-image-builder/issues/620
[0] https://github.com/osbuild/images/commit/54c2e63d76f6e9420f38b24b4022ccdfb64ce602#diff-8428a6822f263c812a988ac0a6548341cba28f9f4526fb6a5f6f53c2346f1b87R197
[1] https://github.com/osbuild/osbuild/pull/1846

distrodefs: tweak dependencies for image installer

---

bib/go.mod
bib/go.sum

There was a regression in the "images" library for building the bootc anaconda-iso that PR#915 [0] fixes.
If the anaconda-iso integration tests work again, then this is good to merge.
[0] https://github.com/osbuild/images/pull/915

bib: update go.mod to include images PR#915

---

bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go
test/test_manifest.py

This commit partially reverts PT#549 to unblock filesystem
customizations in bib.
This is a short term fix and we should revert and do something
smarter like https://github.com/osbuild/images/pull/951 or see
if we can do better in the toml unmarshaling. But to unblock
toml customizations this is a (IMHO) reasonable first step.
Closes: https://github.com/osbuild/bootc-image-builder/issues/655

buildconfig: disable tests for undecoded keys for now

---

bib/internal/container/container.go
test/testcases.py

This is an alternative idea to PR#651 - we run `dnf` inside the
container to init the dnf system. However with `dnf5` this no
longer works and it just throws an error.
So instead we run `dnf check` which should work on both dnf{4,5}.
---
test: move `target-arch-smoke` testcases to Fedora42 (for
dnf5)
This will give us testing for dnf5 as well.
[draft until tests are good and I double checked dnf sources]

container: run `dnf check` in container for dnf4/dnf5 compat

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

Producing a multi-arch image build on the following arches: amd64, arm64, ppc64le and s390x

Multi-arch *4 support

---

README.md
bib/internal/imagetypes/imagetypes.go
bib/internal/imagetypes/imagetypes_test.go
test/test_build.py
test/testcases.py

This commit adds a new image type `raw-tgz` that contains a tar
file with the raw image inside. This was requested by GCP.
See also https://github.com/osbuild/images/pull/923
This will need https://github.com/osbuild/osbuild/pull/1886 first.

bib: add a new `gce` image type (COMPOSER-2358)

---

bib/cmd/bootc-image-builder/main.go

This is a trivial commit that adds a final newline to `bootc-image-builder manifest`.

bib: add final newline after `bib manifest`

---

.github/workflows/tests.yml
bib/cmd/bootc-image-builder/image.go
plans/all.fmf
test/test_build.py
test/testcases.py

Label the anaconda ISO depending on the container OS
and make the ISO label format compatible with libosinfo.
This will make any software using libosinfo to be able
to correctly detect the OS contained in the ISO and
where to find the initrd and the kernel.
Resolves: https://github.com/osbuild/bootc-image-builder/issues/265

Use a libosinfo compatible label format for the Anaconda ISO

---

bib/cmd/bootc-image-builder/image.go

According to [1] neither Docker daemon nor OCI support storing
the container signatures, and skopeo copy refuses to just silently drop
them and fails.
When using `skopeo copy --remove-signatures` to make the copy, the
signatures will be still read and policy.json will still be enforced,
they just won’t be written into the destination.
[1] https://github.com/containers/skopeo/issues/589#issuecomment-453894401

fix: use remove-signatures in skopeo copy stages

---

bib/cmd/bootc-image-builder/image.go

[draft as this assumes an ISO actually makes sense for s390x/ppc64le]
This commit populates the "img.Platform" struct when building for s390x and ppc64le.
No tests right now sadly, this should be looked into but given that it is known broken right now this change can hardly make it worse.
Closes: https://github.com/osbuild/bootc-image-builder/issues/686

image: add platform support for s390x, ppc64le in the ISO

---

README.md
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go
bib/internal/buildconfig/export_test.go

This commit adds support for reading the build config via stdin. To do that the `-config` switch now supports `-` and with that it will use `os.Stdin` insteadof readin the file. Because we have no file extension to auto-detect the format only JSON is supported in this mode.
This feature will be used by osbuild-composer when it adds bootc image mode integration.

buildconfig: support passing build config via `stdin`

---

.github/workflows/tests.yml
test/test_build.py
test/testcases.py
test/testutil.py

Add anaconda-iso iso build tests with signed containers.
The rest of the images can be also added to the test once
[1] and [2] are merged
[1] https://github.com/osbuild/images/pull/990
[2] https://github.com/osbuild/osbuild/pull/1906
Signed-off-by: Miguel Martín <mmartinv@redhat.com>

test: add anaconda-iso build tests with signed containers

---

bib/data/defs/fedora-40.yaml

Add the the python3-pam package to the list of dependencies
as it seems to be required for the anaconda-core rpm.
Resolves: fedora-iot/iot-distro#66
Signed-off-by: Miguel Martín <mmartinv@redhat.com>

fix: add a missing dependency for the anaconda-iso installer

---

.github/workflows/testingfarm-unit.yml
.github/workflows/testingfarm.yml

The testingfarm-unit testplan is wrong, this is why the action is failing. Sadly because of the way it runs (via the `on: pull_request_target`) only what is in `main` will be run so it is hard to test these actions before merging :(

workflow: fix plan filter for `testingfarm{,-unit}` action

---

bib/cmd/bootc-image-builder/image.go

fix: set fips in manifest according to our customizations

---

test/testcases.py

This commit drops the "unsigned" fedora ISO genartion testcases. We also test unsigned ISO generation via centos-9 and we test the fedora ISO generation via the "signed" fedora ISO test so running this specific test gives us little and it is also one of the most "expensive" tests we run (around 10min).

tests: drop (unsigned) fedora ISO testcase

---

.github/workflows/tests.yml

This commit moves the GH runner to move to 24.04. This means we no longer need a extra repository to get a current version of podman and it generally means our software stack is more modern and closer to what version people run.
Note that this also drops "podman,skopeo" as those are preinstalled.
Unfortuantely the default 24.04 podman configuration is buggy and a workaround is needed.
[split out from https://github.com/osbuild/bootc-image-builder/pull/689]

workflow: move workflow to run on ubuntu-24.04

---

bib/internal/container/solver.go
bib/internal/container/solver_test.go

This commit goes back to the approach we had in PR#565 to resolve using
the solver from outside of the container. The reason to back is that
some containers (like f41) do not have the python dnf available so
they break with the "run dnfjson inside" approach (that was meant
as a quick fix only anyway).
Huge kudos to Achilleas for most of the work here.
Closes: https://github.com/osbuild/bootc-image-builder/issues/700
It would be ideal if this could be tested end-to-end on a rhel9 system building a rhel9 iso installer.

bib: resolve container content from the external dnf again

---

bib/cmd/bootc-image-builder/image.go
bib/go.mod
bib/go.sum
package-requires.txt
test/test_manifest.py
test/testcases.py

This PR adds support for the new Disk customizations from https://github.com/osbuild/images/pull/1041 into bib.
Split from https://github.com/osbuild/bootc-image-builder/pull/721 to allow people to experiment easier, getting the integration test right is a bit tedious.

bib: add support for the new Disk customizations

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go

This commit will run ValidateLayoutConstraints() when a `DiskCustomization`
is used.
Similar comment to https://github.com/osbuild/images/pull/1063:

image: run ValidateLayoutConstraints() when using  DiskCustomizations

---

README.md
devel/Containerfile.hack

Using `./` to prefix a path relative to the current directory works just
as well and doesn't require quoting for potential paths with spaces, nor
a subshell.
The `./` prefix (or an abs path) is required when referring to single
local directories with just one path component, otherwise podman
interprets the path as a volume name.

README: drop $(pwd) from volume mounts in podman commands

---

HACKING.md

This commit removes an unnecessary [] in the description.

HACKING.md: remove unneeded `[`,`]` in the description

---

bib/go.mod
bib/go.sum
test/test_build.py
test/test_manifest.py
test/testcases.py
test/testutil.py

[It is draft right now because it has quite a few rough edges in the code but mostly because the LVM case is not working right now and it's unclear why, but pushing it will help with exposure/feedback, there are also some issues in "images" that are uncovered here that should be fixed there (like minsize seems to be not working for strings)]
This PR adds support for the new `Disk` customizations from https://github.com/osbuild/images/pull/1041 into bib.

bib: add integration test for the new `Disk` customizations

---

bib/go.mod
bib/go.sum
test/test_build.py
test/test_manifest.py
test/testcases.py
test/testutil.py

This commit adds an integration test for the new swap disk customization that got added to the `images` library in PR https://github.com/osbuild/images/pull/1072

test: add integration test for the new `swap` customization

---

bib/cmd/bootc-image-builder/export_test.go
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
bib/go.mod
bib/go.sum
test/test_manifest.py
test/testutil.py

This commit improves the rootfs size calculation for advanced
partitioning.  Just like for the tranditional filesystem
customization where we use `updateFilesystemSizes()` to ensure
that the rootfs is at least the two times size of the container
we need to do the same for the advanced disk partitioning.
The disk library will need a `RequiredMinSizes` parameter
(see gh#748) to know what sizes to pick. So far we did not
pass this which can leads to a "0B" root partition.
The naive fix was to just include a hardcoded:
```
requiredDirectorySizes = map[string]uint64{
"/":    1 * datasizes.GiB,
"/usr": 2 * datasizes.GiB,
}
```
but of course that is not ideal because we calculate the
size of disk based on 2x the container size. We set this
for the rootfs so the entire disk is big enough. However …

bib: improve the "/" size calculation for LVM

---

bib/data/defs/centos-10.yaml
test/test_build.py
test/testcases.py

**data/defs/centos-10: drop removed packages**
These packages are no longer part of CentOS Stream 10 (or RHEL 10).
---
**test: run tests with centos-bootc:stream10 as well**
Rename TestCaseCentos to TestCaseS9S and add a TestCaseC10S.
---

Drop removed packages from CentOS Stream 10 and RHEL 10.

---

README.md

Replaces https://github.com/osbuild/bootc-image-builder/pull/674

readme: add project links

---

bib/cmd/bootc-image-builder/cloud.go
bib/cmd/bootc-image-builder/main.go
bib/go.mod
bib/go.sum
bib/internal/progress/export_test.go
bib/internal/progress/progress.go
bib/internal/progress/progress_test.go
test/containerbuild.py
test/test_progress.py

This adds a new `progress` flag that makes use of the
osbuild jsonseq progress information to show progress and
hide the low-level details from the user.
Here is what it looks like:
https://asciinema.org/a/cJpB6066UoDDzAylwHVHjEEIN
(c.f. COMPOSER-2394)

main,osbuildprogress: add --progress=text,debug support (COMPOSER-2394)

---

bib/internal/progress/progress.go
bib/internal/progress/progress_test.go

This commit fixes the missing \n when plain progress is used. Without the output looks rather silly :/

progress: fix missing "\n" in plain progress

---

bib/cmd/bootc-image-builder/main.go

Improve command line help
Some texts have been missing

bootc-image-builder/main: improve command line help

---

bib/internal/progress/export_test.go
bib/internal/progress/progress.go
bib/internal/progress/progress_test.go
test/test_progress.py

This commit adds automatic progress bar selection based on checking
if we run on a terminal or not. When running on a terminal we use
the nice "terminalProgressBar". If that is not set we assuem
we run in a script or CI/CD environment and select plainProgressBar.
Thanks Colin for the hint about the bad integration test.

progress: auto-select progress based on the environment

---

bib/data/defs/almalinux-10.yaml
bib/data/defs/almalinux-9.yaml

Makes it possible to build images based on Alma Linux bootc containers, such as `quay.io/almalinuxorg/almalinux-bootc:9.5`
Fixes #753

Add manifests for Alma Linux 9 and 10

---

Containerfile

Fedora N-1 (40 now) is stable, but will eventually get stale. In my case we happen to be using this image as a "builder" image and I added a new feature to rpm-ostree, which I didn't ship to F40. I may still do so.
However it's clearly a good idea for us to keep updated.
This all said, it's actually not clear to me that Fedora is the right default base image - it may make sense to target e.g. c10s or c9s?
This all relates to https://gitlab.com/fedora/bootc/tracker/-/issues/2 as well.

build-sys: Bump to Fedora 41

---

.github/workflows/tests.yml
bib/cmd/bootc-image-builder/image.go
test/testcases.py

This commit enables bib to work with the qemu-9.1+openat2 patches as proposed in https://src.fedoraproject.org/rpms/qemu/pull-request/69.
With the qemu-user-statuc-aarch64 rpm produced by `fedpkg mockbuild` from this package the cross-arch test build works again.
```
$ sudo PYTHONPATH=. pytest './test/test_build.py::test_image_boots[quay.io/centos-bootc/centos-bootc:stream9,raw,CentOS Stream 9 ({arch}),arm64]' -s -vv
============================= test session starts ==============================
platform linux -- Python 3.12.7, pytest-7.4.3, pluggy-1.3.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/mvogt/devel/osbuild/bootc-image-builder
configfile: pytest.ini
plugins: repeat-0.9.3, xdist-3.5.0
collected 1 item
test/test_build.py::test_image_boots[quay.io/centos-bootc/centos …
```

bib: remove usage of `BootcLegacyDiskImage` (for qemu-9.1)

---

README.md
bib/cmd/bootc-image-builder/cloud.go
bib/cmd/bootc-image-builder/main.go
bib/internal/progress/export_test.go
bib/internal/progress/progress.go
bib/internal/progress/progress_test.go

This PR adds some missing documentation around the new `--progress` switch. This hopefully helps with the questions/uncertainty raised in e.g. https://github.com/osbuild/bootc-image-builder/pull/765

main,README: improve docs around `--progress`

---

.github/workflows/tests.yml
bib/cmd/bootc-image-builder/image.go
bib/go.mod
bib/go.sum
test/test_build.py
test/test_manifest.py

This commit moves to the new "flat" squashfs rootfs image
that is now available in the `images` library (c.f.
https://github.com/osbuild/images/pull/1105).
This will ensures we are no longer using the previous "ext4"
intermediate image that gave problems for big rootfses.
Closes: https://github.com/osbuild/bootc-image-builder/issues/733

bib: use plain squashfs for the ISO rootfs

---

README.md
bib/cmd/bootc-image-builder/main.go
bib/cmd/bootc-image-builder/main_test.go
test/test_opts.py

This commit adds `--verbose,-v` which will increase the verbosity
of logrus and also switch the --progress to "verbose". This is
addressing the feedback we got in
https://github.com/osbuild/bootc-image-builder/pull/765
and a followup for #776
The new `-v` clashes unfortunately with cobras default for version,
so there is no single dash flag for version anymore. Most unix tools
(e.g. cp,rsync,mv,curl,ssh,tar) use "-v" for "--verbose" so IMHO we
should follow suite. Unfortuantely there is no consistency in linux,
e.g. git,gcc are counter examples where it means version). I would
still go with -v for verbose as ssh,tar,curl are probably used
more often to get verbose output.
---
main,test: tweak cmdVersion
This commit tweak the new and very nice functionality of cmdVersion (see commit …

main: add --verbose,-v persistent flag that increases  verbosity

---

README.md

This commit updates the documentation around the supported flags. It also switches on "bold" for a smaller subset of the important flags.
Note that still not all flags are shows, some are documented below (like the `--aws-*`) and some (like --store, --rpmmd) require more context, i.e. explaining that they require calling podman with the right `--volume` mappings.

README.md: update supported flags table

---

plans/integration.fmf

We recently hit the issue that bootc-image-builder is no longer releasing. It turns out we hit the limit of our integration tests. Increase this limit for now.

plan: give testingfarm more time to complete

---

bib/go.mod
bib/go.sum

This commit updates the images library version to work with the latest version of osbuild with "modules" support.

go.mod: update to latest images to unbreak osbuild integration

---

README.md

SELinux may not be enforced, e.g. as is the case on Debian.
Ported over from https://github.com/osbuild/osbuild.github.io/pull/138
Please note that I'm not the original author of this suggestion, I merely wanted to help @egodigitus by re-opening the change in the correct place.

README: Clarify optional SELinux dependency

---

bib/pkg/progress/export_test.go
bib/pkg/progress/progress.go
bib/pkg/progress/progress_test.go

This commit adds catpure of os.Std{out,err} when running osbuild so that we capture the error log and can display it as part of an error from osbuild, e.g. when osbuild itself crashes.
This gives us more accurate error reporting if anything fails during the osbuild building.
[edit: this will also help https://github.com/osbuild/image-builder-cli/pull/21]

progress: tweak progress error reporting

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/main.go
bib/internal/setup/setup.go
test/test_build.py
test/test_manifest.py
test/test_opts.py
test/test_progress.py
test/testcases.py
test/testutil.py

Pulling container images before building would break in the case of authenticated images on podman machine, since the auth file lives on the host and podman machine and won't know about it.
This commit deprecates the `--local` flag and puts the requirement on the user to ensure that the container is in local storage before initiating the build.

Deprecate `--local` flag (HMS-3792)

---

bib/pkg/progress/progress.go
bib/pkg/progress/progress_test.go

This commit fixes a silly mistake from PR#810. The issue is that in #810 we started to collect the osbuild stdout/stderr so that we can show crashes from osbuild or other unexpected output.
However when a stage fails this is reported via the json progress and not directly on stdout/stderr - this was missed when #810 was done.
This commit does a short term fix by collecting the buildlog again and showing it in the error and also updates the test to be more realistic. However we really need a test that actually tests the real behavior, ideally a real osbuild run with a stage error so that we can be sure we capture this (criticial!) functionality.

progress: fix missing build log output on errors in progress

---

test/testcases.py

This commit switches centos-9 to use librepo as well. This is a bit sad because it means we have no repo anymore that uses the default "curl" backend. But even the centos9 mirrors are now so unreliable that we cannot get things merged.
We should switch the default downloader here to librepo but we need some downstream test that ensures that subscribed content can still be installed with librepo (it should work but there is no explicit test in our testsuite).
(failing test, e.g. https://github.com/osbuild/bootc-image-builder/actions/runs/13134326900/job/36704112622?pr=818, re-run three times now)

test: use `librepo` for `centos-9` too

---

bib/pkg/progress/export_test.go
bib/pkg/progress/progress.go

This commit changes the way `os.Stderr` is mocked so that higher level consumes of the libary can use helpers can replace os.Stderr (like `testutil.CaptureStdio()` is doing). The existing approach assigns the "real" os.Stderr to osStderr so early that it cannot be changed later.
This will allow the test outlined in https://github.com/osbuild/image-builder-cli/pull/124

progress: tweak how `os.Stderr` is mocked

---

bib/internal/distrodef/distrodef.go
bib/internal/distrodef/distrodef_test.go

This commit fixes the issue that when the `os-release` has an
`ID=10.0` in it, a distrodef file ending with `-10` will not
be identified as the closest match because the code is using
a "strictly bigger" relation to sort versions but for semver
`10.0` and `10` are just identical so we need ">=" instead
of ">" (see the actual diff).
We saw this issue with the `rhel-10.0` beta that has a
`VERSION_ID=10.0` field and a `rhel-10.yaml` distro-def. Here the
code was skipping over rhel-10.yaml and felt back to rhel-9 when
it really should have used `rhel-10.yaml`.
Thanks to Achilleas for tracking this down.

distrodef: fix incorrect detection of `centos-10` vs `10.0`

---

Makefile

Implement `make help` to be more developer friendly

Makefile: implement `make help`

---

.github/workflows/tests.yml

For some reason the linter fails but also the golang version should be consistent with `go.mod`

github/workflows/tests: fix linter by adapting versions

---

test/containerbuild.py
test/test_progress.py

This commit adds a proper integration test that ensures that we
always report the details of a failing osbuild run. This prevents
regressions like the one from #810.
This ensures that:
a) we report the messags from a broken stage
b) we report any osbuild messages as well to catch e.g.
crashes that are not reported via the json progress
It is archived by creating a new build container fixture that is
deliberately broken, i.e:
a) the org.osbuild.selinux stage is replaced with a fake that
will echo some msgs and then error
b) osbuild itself is is wrapped around so that we can reliably
echo some canary strings before the real osbuild is executed

test: add integration test for reporting errors from osbuild

---

bib/pkg/progress/progress.go
bib/pkg/progress/progress_test.go
test/test_build.py
test/testcases.py
test/testutil.py

go.mod: upadate to latest `images` to get PR#1200
This commit updates the images library to pull in the fix [0] for
the overly long messages from osbuild. This should test the
(previously) failing test that runs the centos-9 ISO with an
attached terminal.
[0] https://github.com/osbuild/images/pull/1200
---
test: run the centos-9 test with an attached terminal
This commit changes the centos-9 test to run with `podman -t` so
that we have a test-case that uses the `terminal` progress. This
is prompted by:
a) we have no integration test currently that uses the terminal
progress for the full build
b) a konflux failure/memory leak that showed because there the
test is run with `-t`
----
This commit ensures that we do restrict the memory of the bib
test conatiner to catch excessive memory usage. …

many: deal with incorrect status from osbuild better

---

bib/data/defs/fedora-40.yaml

According to the anaconda team we should be using the `anaconda-install-img-deps`
metapackage to install all the boot.iso image dependencies.
Relates: #707
Relates: fedora-iot/iot-distro#66
Signed-off-by: Miguel Martín <mmartinv@redhat.com>

fix: install anaconda-install-img-deps package in anaconda installers.

---

bib/cmd/bootc-image-builder/main.go
bib/pkg/progress/export_test.go
bib/pkg/progress/progress.go
bib/pkg/progress/progress_test.go
bib/pkg/progress/syncwriter.go
bib/pkg/progress/syncwriter_test.go

This commit adds a new `BuildLog` option to the `OSBuildOptions`
that can be used to generate a streamed buildlog (e.g. to a file
or a websocket).

progress: add new `BuildLog` option

---

.tekton/bootc-image-builder-pull-request.yaml
.tekton/bootc-image-builder-push.yaml

This change solve the konflux build failure in https://github.com/osbuild/bootc-image-builder/pull/767 which is a prerequisite for builash task migration, see https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-remote-oci-ta/0.3/MIGRATION.md. We did the same for the downstream bib pipeline.

Drop JAVA_COMMUNITY_DEPENDENCIES

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
bib/cmd/bootc-image-builder/main_test.go
bib/go.mod
bib/go.sum
test/test_build.py
test/test_manifest.py

This commit adds support for files/directories in blueprint
customizations.
This needs https://github.com/osbuild/images/pull/1227
Closes: https://github.com/osbuild/bootc-image-builder/issues/834
[edit this will also need an update in https://osbuild.org/docs/user-guide/blueprint-reference/#files-and-directories once merged]

bib: add support for file/directory customizations

---

.tekton/bootc-image-builder-push.yaml

Do not trigger push pipeline if only tekton files are updated

Do not trigger push pipeline if only tekton files are updated

---

bib/go.mod
bib/go.sum
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go

This PR enables https://github.com/osbuild/bootc-image-builder/pull/549 again. 
With the new version of burntSushi/toml we have a fix for https://github.com/burntSushi/toml/issues/425 so we can enable strict checking again.

Enable strict toml checks again

---

bib/cmd/bootc-image-builder/main.go

[draft as I want to double check with QE first that we have good coverage for subscribed content testing in the downstream tests]
When building the anaconda-iso from centos or fedora there is a high chance to hit a bad mirror. The libcurl method is not able to fallback to different mirrors so the user experience is bad. Switch to librepo by default therefore.
Closes: https://github.com/osbuild/bootc-image-builder/issues/835

main: switch to librepo by default

---

bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go

This reverts commit c4c3470691d84300aa5fabf948964a6f40e05eda.
This causes issue because we lack toml keys for "Type"

Reapply "buildconfig: disable tests for undecoded keys for now"

---

bib/go.mod
bib/go.sum
test/test_manifest.py

A major part of this update is the ability to use mount units instead of defining mountpoints in /etc/fstab.
For bootc disk images, this is always enabled [1] and requires no further configuration.
Closes #756
[1] https://github.com/osbuild/images/commit/43f1a3251aa37617334bfca7ecb742e86b821449

go.mod: update osbuild/images to v0.128.0

---

bib/cmd/bootc-image-builder/main.go

This commit adds support for more debug for `qemu-user` options. When settings:
```
$ sudo IMAGE_BUILDER_EXPERIMENAL=debug-qemu-user bootc-image-builder ...
```
extra debug from qemu-user will be printed.
This hopefully helps to track down the root cause of https://github.com/podman-desktop/extension-bootc/issues/1475

bib: add experimental flag `debug-qemu-user`

---

test/test_build.py

This commit enables testing for centos10 based installer images.
The fix https://gitlab.com/libosinfo/osinfo-db/-/commit/fc811ba5a792967e22a0108de5a245b23da3cc66 is now released.

test: enable `osinfo_for()` centos10

---

bib/cmd/bootc-image-builder/image.go
bib/internal/source/source.go
bib/internal/source/source_test.go

This commit flips the detection if we need the rhel lorax template. It will only use it when it detect running on rhel/centos/eln. This should help with the common case of distros that need the generic lorax template but do not set the name to fedora.
This might help with the immediate issue in https://github.com/osbuild/bootc-image-builder/issues/904 but is probably useful on its own (as the generic lorax template is the (more) common case).

image: set `UseRHELLoraxTemplates` only on rhel/centos/eln

---

.github/workflows/tests.yml
test/test_build_disk.py
test/test_build_iso.py
test/test_progress.py

This commit moves the test running into a matrix so that
we get more parallel testing. It will still be (much) dominated
by `test_build_disk.py` but at least this way a flaky test in
e.g. `test_container` is much faster to re-run.
With multiple VMs we can probably also parallelize the tests [1]
because we have less images per VM to test so diskspace
may be less of an issue.
---
test: split test_build.py into test_build_{disk,iso}
Split this big test into smaller files because we
will run the tests in parallel via a dynamic (per-file)
github matrix. This will allow faster tests and easier
re-runs if a single test is flaky only a small subset
will have to be retriggered.
[1] https://github.com/osbuild/bootc-image-builder/pull/787

workflow: run pytests via matrix to get more parallel runs

---

.github/workflows/tests.yml
Makefile
bib/cmd/bootc-image-builder/cloud.go
bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
bib/cmd/bootc-image-builder/main.go
bib/cmd/upload/main.go
bib/internal/buildconfig/config.go
bib/internal/buildconfig/config_test.go
test/test_manifest.py

This is the alternative implementation to #891 (and #890 )
Which ignores the defer file.Close() remarks of the linter.
Only for the file where we write to we return an error message, similar message as we do _while_ writing.

Update golangci lint "ignore version"

---

test/test_build_cross.py
test/test_build_disk.py
test/testcases.py

This commit moves the cross arch build into its own file
so that it ran run in parallel in the GH runners. Its is
a relatively expensive test (~20min on my machine) so
moving it out should save quite a bit of time.

test: split cross-arch test into its own file

---

Makefile

We currently see errors in bib CI like:
```
Error: Failed to run: Error: requested golangci-lint version 'v2.0.2' isn't supported: we support only v2.1.0 and later versions, Error: requested golangci-lint version 'v2.0.2' isn't supported: we support only v2.1.0 and later versions
```
(c.f. https://github.com/osbuild/bootc-image-builder/actions/runs/14831005614/job/41632016536?pr=906)
So bump the version to fix this.

Makefile: bump version of golang-ci to 2.1.6

---

bib/cmd/bootc-image-builder/main.go
test/test_manifest.py

All platforms where `bootc-image-builder` runs that have `qemu-user` available have upgrade to a version >= 9.1.0.

main: drop rootfs cross-arch disable

---

bib/cmd/bootc-image-builder/image.go

github.com/osbuild/images v0.124.0 introduced `img.ISOBoot`. This field must be set to either `SyslinuxISOBoot` or `Grub2ISOBoot` for the ISO to boot on BIOS systems.
See: https://github.com/osbuild/images/pull/1289
Closes: https://github.com/osbuild/bootc-image-builder/issues/912

image: set ISOBoot to Grub2ISOBoot for x86_64

---

test/containerbuild.py

The current caching of the test containers can lead to unexpected results when e.g. the upstream osbuild repo gets updated but podman caches the relevant line in the Containerfile because the install of osbuild has not changed. To counter this the container building sets an agressive TTL of 1h for the cache.
This fixes the issues locally.

test: set the cache-ttl to 1h in our tests

---

test/testcases.py

This commit disabled the `TestCaseFedora43` fow now because it fails in CI with:
```
...
org.osbuild.bootc.install-to-filesystem: 19bb778fae4541936924e98952fc101eabf7f1782856dd0447ae1fef4ad3ac61 {
"kernel-args": [
"rw",
"console=tty0",
"console=ttyS0",
"systemd.journald.forward_to_console=1"
],
"target-imgref": "quay.io/fedora/fedora-bootc:43"
}
device/disk (org.osbuild.loopback): loop0 acquired (locked: False)
mount/- (org.osbuild.btrfs): mounting /dev/loop0p4 -> /store/tmp/buildroot-tmp-e004ml_u/mounts/
mount/boot (org.osbuild.xfs): mounting /dev/loop0p3 -> /store/tmp/buildroot-tmp-e004ml_u/mounts/boot
mount/boot-efi (org.osbuild.fat): mounting /dev/loop0p2 -> /store/tmp/buildroot-tmp-e004ml_u/mounts/boot/efi
Mount transient overlayfs for /etc/containers
Creating bind mount for …
```

test: disable `fedora-43` bootc test for now

---

README.md
bib/cmd/bootc-image-builder/image.go
bib/internal/buildconfig/config.go
bib/internal/source/source.go
bib/internal/source/source_test.go
test/test_build_disk.py
test/test_manifest.py

This allows bootc images to embed a  file in `/usr/lib/bootc-image-builder` in the image called `config.json` or `config.toml`, which specify more detailed requirements for the  partitioning. From this (which is in the full blueprint format) we extract (only) the disk and/or filesystem customization part.
This is useful to either add extra partitions (like a separate /var), or to override details of the normal partitions (like uuids, labels, etc).
This is discussed in https://github.com/bootc-dev/bootc/issues/926
I used the entire blueprint format so that we can reuse existing docs, and so that we can later use more customization fields if needed.
Note: This (mostly trivially) conflicts with https://github.com/osbuild/bootc-image-builder/pull/928

Apply disk or filesystem customization from embedded image customization

---

bib/cmd/bootc-image-builder/image.go
bib/cmd/bootc-image-builder/image_test.go
bib/cmd/bootc-image-builder/main.go
bib/go.mod
bib/go.sum
bib/internal/source/source.go

This is some initial work for supporting bootc in the automotive projects. It includes the following:
* Extract the active selinux policy from the image
* Support specifying a custom build container image ref
This depends on: https://github.com/osbuild/images/pull/1519

Automotive initial work

---

bib/cmd/bootc-image-builder/main.go
test/test_progress.py

I almost always stop people who say "image" without qualification because disk images are very different from container images. There's a lingering confusion that bootc-image-builder builds bootc images, which is not true...

Clarify we build disk images

---

test/testcases.py

The bootc fedora43 install was failing but with:
https://github.com/bootc-dev/bootc/pull/1337
this should now be fixed (thanks Colin!).
Closes: https://github.com/osbuild/bootc-image-builder/issues/934

test: re-enable Fedora43 test

---

test/testcases.py

This reverts commit e37bb8350b98900b2c2682319544eeeee7e00ecf.
Because https://github.com/osbuild/bootc-image-builder/issues/965 seems to be fixed.

Revert "test: disable anaconda-iso C10S test for now"

---

test/test_build_disk.py

This commit uses a randomized password for the test user in the test VM.

test: use randomized password for test VMs

---

Containerfile
plans/integration.fmf
test/test_build_disk.py

test: enable `OSBUILD_EXPERIMENTAL=debug-qemu-user`
This commit enables OSBUILD_EXPERIMENTAL=debug-qemu-user
during the tests so that we see what unimplemented syscalls
or ioctls are used.
This should help with the cross-arch failure debugging we
see in tmt right now.
---
plan: add `osbuild-{lvm2,ostree}` to tmt test
This commit adds the missing `osbuild-{lvm2,ostree}` to
integration.fmf so that the manifest lvm tests work.
---
test: skip the test_image_build_without_se_linux_denials
Skip the test_image_build_without_se_linux_denials test until
https://github.com/osbuild/bootc-image-builder/issues/645 is
resolved.
It pains me to do this but the test is failing for some time
and bib itself cannot do anything to resolve this (AIUI it
need an upstream selinux policy change so that install_t …

test: fix various testing-farm issue

---

bib/go.mod
bib/go.sum

We have an issue where `%post` scripts are not being executed due to our incorrect handling of Anaconda modules [1].
[1]: https://github.com/osbuild/bootc-image-builder/issues/968

deps: bump images to 0.164

---

.github/workflows/build.yaml

At some point we stopped building and pushing the container to ghcr to focus on having only Konflux builds and a single source of the upstream (though, more like "midstream") container on quay.io.  However, Konflux builds are not entirely reliable and are inaccessible to external users and contributors.  So while the container itself is publicly available under the quay.io/centos-bootc namespace, investigating (and solving) build failures requires contacting people with access to the private job logs.
Re-enabling ghcr builds allows us (and practically anyone) to easily investigate and solve build failures and gives us a reliable upstream container available shortly after every PR is merged, making troubleshooting against the latest version a lot easier.
This reverts commit …

github: publish upstream container to ghcr

---

bib/go.mod
bib/go.sum
test/test_manifest.py

**go.mod: update osbuild/blueprint to v1.11.0**
Fixes #1004
---
**test: add manifest test for partition table type**
---

Fix partition table type customization being ignored

---

test/testcases.py

This commit disables the centos9 iso test because it currently crashes the centos9 kernel, see
https://issues.redhat.com/browse/RHEL-109635
This unbreaks bib merges and should be reverted once RHEL-109635 is fixed.

test: disable centos9 iso test for now because kernel panic

---

test/test_manifest.py
test/testcases.py

We had this test disabled for a while because the mirror situation was not very stable. With librepo by default and some time having passed we should try it again.

test: re-enable the fedora 42 iso test

---

bib/cmd/bootc-image-builder/image.go
bib/go.mod
bib/go.sum

bib: move bib to new platform.Data{}
In images https://github.com/osbuild/images/pull/1739 we
dropped the hardcoded platforms. Bib needs to follow suite
and this commit does it now.
---
go.mod: update for images v0.179.0
Thanks to Alex!

bib: move to images v0.179.0

---

bib/cmd/bootc-image-builder/main.go
bib/go.mod
bib/go.sum
test/test_manifest.py

Bump the images dependency to 0.191.0 and handle the rename of `dnfjson` to `depsolvednf`.

deps: update images to 0.191.0

---

test/testcases.py

[draft because we obviously can only revert this once https://issues.redhat.com/browse/RHEL-109635 is fixed but opening it so that this is not forgotten]
This reverts commit 70f03adc0dec7dcd15b7476e00fd1c3975930c57.
(c.f. https://github.com/osbuild/bootc-image-builder/pull/1019)

Revert "test: disable centos9 iso test for now because kernel  panic"
